# .app-env: &app-env
#   PG_POOL_MAX: "${PG_POOL_MAX}"
#   POSTGRES_CONN: "${POSTGRES_CONN}"
#   LOG_LEVEL: "${LOG_LEVEL}"
#   HTTP_PORT: "${HTTP_PORT}"
#   HTTP_USE_PREFORK_MODE: "${HTTP_USE_PREFORK_MODE}"

# .db-env: &db-env
#   POSTGRES_HOST: ${POSTGRES_HOST}
#   POSTGRES_PORT: ${POSTGRES_PORT}
#   POSTGRES_USER: ${POSTGRES_USERNAME}
#   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#   POSTGRES_DB: ${POSTGRES_DATABASE}

services:
  go_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: "${APP_NAME}"
      APP_VERSION: "${APP_VERSION}"
      PG_POOL_MAX: "${PG_POOL_MAX}"
      POSTGRES_CONN: "${POSTGRES_CONN}"
      LOG_LEVEL: "${LOG_LEVEL}"
      HTTP_PORT: "${HTTP_PORT}"
      HTTP_USE_PREFORK_MODE: "${HTTP_USE_PREFORK_MODE}"
      # ↓ Новые переменные для HDFS ↓
      HDFS_ADDR: "${HDFS_ADDR}"
      HDFS_ENABLED: "${HDFS_ENABLED}"
    image: go_app
    container_name: "server"
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    restart: unless-stopped
    depends_on:
      - db
      - datanode # ← ждём HDFS
    networks:
      - internet

  db:
    image: postgres:16
    container_name: "db_postgres"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internet

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    env_file:
      - hadoop.env
    networks:
      - internet

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    depends_on:
      - namenode
    ports:
      - "9864:9864"
      - "9866:9866"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    env_file:
      - hadoop.env
    networks:
      - internet

volumes:
  postgres_data:
  hadoop_namenode:
  hadoop_datanode:

networks:
  internet:
    name: internet
    driver: bridge
