# .app-env: &app-env
#   PG_POOL_MAX: "${PG_POOL_MAX}"
#   POSTGRES_CONN: "${POSTGRES_CONN}"
#   LOG_LEVEL: "${LOG_LEVEL}"
#   HTTP_PORT: "${HTTP_PORT}"
#   HTTP_USE_PREFORK_MODE: "${HTTP_USE_PREFORK_MODE}"

# .db-env: &db-env
#   POSTGRES_HOST: ${POSTGRES_HOST}
#   POSTGRES_PORT: ${POSTGRES_PORT}
#   POSTGRES_USER: ${POSTGRES_USERNAME}
#   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#   POSTGRES_DB: ${POSTGRES_DATABASE}

services:
  go_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # <<: *app-env
      APP_NAME: "${APP_NAME}"
      APP_VERSION: "${APP_VERSION}"
      PG_POOL_MAX: "${PG_POOL_MAX}"
      POSTGRES_CONN: "${POSTGRES_CONN}"
      LOG_LEVEL: "${LOG_LEVEL}"
      HTTP_PORT: "${HTTP_PORT}"
      HTTP_USE_PREFORK_MODE: "${HTTP_USE_PREFORK_MODE}"
    image: go_app
    container_name: "server"
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - internet

  db:
    image: postgres:16
    container_name: "db_postgres"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      # <<: *db-env
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internet

volumes:
  postgres_data:

networks:
  internet:
    name: internet
    driver: bridge
