DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS templates CASCADE;
DROP TABLE IF EXISTS rentpoints CASCADE;

DROP TYPE IF EXISTS status_order_type CASCADE;
DROP TYPE IF EXISTS status_product_type CASCADE;